apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger-query.monitoring.svc.cluster.local:16686
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
