apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - hooks/job-presync-migrate.yaml
  - hooks/job-postsync-health.yaml
  - hooks/job-syncfail-slack.yaml
